### PR TITLE
Add a Bitdeli Badge to README

### PR DESCRIPTION
**Pull request by bitdeli-chef**
Pull request made by @kpdecker at https://bitdeli.com

### CODE REVIEW

**Comment by patrickkettner** [comment]
Any interest in adding any other badges while we are at it?

**Comment by kpdecker** [comment]
@patrickkettner what are you thinking?

**Comment by patrickkettner** [comment]
there are

[travis build status](http://about.travis-ci.org/docs/user/status-images/)
[Gemnasium dependency status](https://gemnasium.com)
[latest npm verison](http://www.gemfury.com/)
[tons of types of counters from sourcegraph](https://sourcegraph.com/help/authors/getting-started)
[code climate GPA score](https://codeclimate.com/)
[coveralls test coverage status](https://coveralls.io/)

to name a few.

also, you might want to move the badge to the top, so its more discoverable. Unless you didn't want it to be as visible to people.

**Comment by patrickkettner** [comment]
Released in 1.3.1

**Pull request merged**
