### PR TITLE
allow customizable config using ms_admin

### PR DESCRIPTION
**Pull request by jhudson8**
will allow QA testing of A/B functionality w/o server restarts & config changes

### CODE REVIEW

**Comment by jhudson8** [comment]
:)

**Comment by jhudson8** [comment]
I'm only allowing valid JSON before submitting the form so I don't see how it would throw.

**Comment by kpdecker** [comment]
`curl /ms_admin/config?config=goFuckYourselfServer`

**Comment by jhudson8** [comment]
I'll add a try/catch - IMHO, this doesn't really need to protect against something like that since it is not for production use but it certainly doesn't hurt

**Comment by jhudson8** [comment]
oh and, I like your example btw

**Comment by kpdecker** [comment]
I guess my point is more that this is intended to be accessed on a public endpoint. We should do at least a bit of hardening so it's not easy to crash/hijack the thing.

**Comment by kpdecker** [comment]
Released in 1.2.0

**Pull request merged**
